### ISSUE TITLE
arrays and loops

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#10]

**Comment by Bookcliff** [comment]
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#array_methods
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

**Comment by RusseII** [comment]
Nice - probably a big more granular checklist than you need lol but if it works for you! 

You can also edit the OP comment instead of making another comment 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/15036618/167644720-439f4c8f-ba6e-42c9-8888-e20544d4d3e5.png">

**Comment by RusseII** [comment]
Reopening to add the original doc that was supposed to be linked here. Feel free to skim through it quickly if you already learned it all.

 - [x] [arrays and loops](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/4-arrays-loops/README.md)
