### ISSUE TITLE
Learn about .map, .forEach, .filter

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#4]
Do this after #10. 
Learn about 
- [x] [.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
- [x] [.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
- [x]  [.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

This is the main way you'll be iterating through arrays. You can close this issue when you can answer the following questions: 
- [x] When would you use forEach? 
- Use arr.forEach when you need to iterate over an array, map, or set and apply a callback function to each element of that object.
- [x] Why use forEach instead of a for loop? 
- arr.forEach is a more semantic and intuitive method of iterating over an array than a for() loop. However, I also came across an [article](https://coderwall.com/p/kvzbpa/don-t-use-array-foreach-use-for-instead) saying arr.forEach is slower than a for() loop so if you are optimizing speed it may be more helpful to use a for() loop in that specific case? 
- [x] When use .map? 
- Use .map whenever you want to create a new array from an existing array. .map does not change the existing array.

**Comment by RusseII** [comment]
Do this after #10. This is the main way you'll be iterating through arrays. You can close this issue when you can answer the following questions: 
- [] When would you use forEach? 
- [] Why use forEach instead of a for loop? 
- [] When use .map?

**Comment by RusseII** [comment]
> Use arr.forEach when you need to iterate over an array, map, or set and apply a callback function to each element of that object.

Yep, correct! Also - It's almost always arrays. I can't remember the last time I used a set or a map data type. 

> arr.forEach is a more semantic and intuitive method of iterating over an array than a for() loop. 

Yep! 

> so if you are optimizing speed it may be more helpful to use a for() loop in that specific case?

Probably not. Over optimizations like that are almost never worth it. There are some niche use cases to use a regular for loop with async code. We'll talk more about that after you learn about promises 

> Use .map whenever you want to create a new array from an existing array. .map does not change the existing array.

Yep exactly. One of the most common noob mistakes is using `.map` when they should be using `.forEach`
