### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#7]
- [x] [variables](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/1-data-types/README.md)

**Comment by Bookcliff** [comment]
Use const by default (denote that the variable is assigned the value and cannot be changed)
Use let within loops (can be reassigned on each iteration)

const newVar = 123;

let newVar = 123;

Primitive data types: string, number, bigint, boolean, symbol, undefined, null

**Comment by RusseII** [comment]
> Primitive data types: string, number, bigint, boolean, symbol, undefined

Is `null` one as well?
