### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#8]

**Comment by Bookcliff** [comment]
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions#constructor_vs._declaration_vs._expression
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by RusseII** [comment]
reopening please do 
- [x] [functions](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/2-functions-methods/README.md)
