### ISSUE TITLE
decisions

### ISSUE THREAD

**Issue by Bookcliff** [Bookcliff/learning#9]
- [x] [decisions](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/3-making-decisions/README.md)

**Comment by Bookcliff** [comment]
if...else statement:
if (currentMoney >= laptopPrice) {
    console.log("I'm getting a new laptop!")
} else {
    console.log("No laptop for me :(")
}

Ternary expression:
currentMoney >= laptopPrice ? ("I'm getting a new laptop!"): ("No laptop for me :(");

**Comment by RusseII** [comment]
that example is funny. Usually you'll either assign the result to a variable, or return it from a function.

`const result = currentMoney >= laptopPrice ? ("I'm getting a new laptop!"): ("No laptop for me :(");`
or
`return currentMoney >= laptopPrice ? ("I'm getting a new laptop!"): ("No laptop for me :(");`

or to match your first example...

`console.log(currentMoney >= laptopPrice ? ("I'm getting a new laptop!"): ("No laptop for me :(");)`

**Comment by RusseII** [comment]
Ternary is used a lot.
